### ISSUE TITLE
macOS builds should have run_exports max_pin="x.x.x"

### ISSUE THREAD

**Issue by traversaro** [conda-forge/sdl2_ttf-feedstock#18]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I do not know if this is a problem upstream or it is a deliberate decision, but some some reason it seems that macOS CMake config files for `sdl2_ttf` ask downstream build systems to link the specific patch version of the library, creating a runtime dependency not on any sdl2_ttf version newer then the version used, but exactly on the patch version of sdl2_ttf used to build the package. 

To understand why is happening, see the content of `lib\cmake\SDL2_ttf\SDL2-shared-targets-release.cmake` file from `osx-64/sdl2_ttf-2.22.0-hcf92afd_0.conda`, its content is:
~~~
#----------------------------------------------------------------
# Generated CMake target import file for configuration "Release".
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Import target "SDL2_ttf::SDL2_ttf" for configuration "Release"
set_property(TARGET SDL2_ttf::SDL2_ttf APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SDL2_ttf::SDL2_ttf PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "SDL2::SDL2"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libSDL2_ttf-2.0.2201.0.0.dylib"
  IMPORTED_SONAME_RELEASE "@rpath/libSDL2_ttf-2.0.2201.0.0.dylib"
  )

list(APPEND _cmake_import_check_targets SDL2_ttf::SDL2_ttf )
list(APPEND _cmake_import_check_files_for_SDL2_ttf::SDL2_ttf "${_IMPORT_PREFIX}/lib/libSDL2_ttf-2.0.2201.0.0.dylib" )

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
~~~

Note how the `IMPORTED_SONAME_RELEASE` refers to the exact name of the library, not to the `libSDL2_ttf-2.0.dylib` or `libSDL2_ttf.dylib` symlink. On the other hand, the same `lib\cmake\SDL2_ttf\SDL2-shared-targets-release.cmake` file in the `linux-64/sdl2_ttf-2.22.0-ha14f88b_0.conda` linux package is :

~~~
#----------------------------------------------------------------
# Generated CMake target import file for configuration "Release".
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Import target "SDL2_ttf::SDL2_ttf" for configuration "Release"
set_property(TARGET SDL2_ttf::SDL2_ttf APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SDL2_ttf::SDL2_ttf PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "SDL2::SDL2"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libSDL2_ttf-2.0.so.0.2200.0"
  IMPORTED_SONAME_RELEASE "libSDL2_ttf-2.0.so.0"
  )

list(APPEND _cmake_import_check_targets SDL2_ttf::SDL2_ttf )
list(APPEND _cmake_import_check_files_for_SDL2_ttf::SDL2_ttf "${_IMPORT_PREFIX}/lib/libSDL2_ttf-2.0.so.0.2200.0" )

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
~~~

In this case, the `IMPORTED_SONAME_RELEASE` referece to the generic x.x name of the library, not to the x.x.x name of the library.

### Installed packages

```shell
osx-64/sdl2_ttf-2.22.0-hcf92afd_0.conda
```

### Environment info

```shell
Not relevant.
```

**Comment by traversaro** [comment]
It seems that the same problem affects the `sdl2_image` package, while the `sdl2` package seems to have a different style/logic of CMake config files.

**Comment by h-vetinari** [comment]
Hm, interesting. The info in the abi-lab is not very [extensive](https://abi-laboratory.pro/index.php?view=timeline&l=sdl_ttf), but generally looks like there's only symbol additions (so, compatible). Similarly for [sdl_image](https://abi-laboratory.pro/index.php?view=timeline&l=sdl_image).

I think it might be reasonable here to just patch the generation of the CMake config on OSX, ideally coupled with an upstream issue discussing the situation (perhaps I'm overlooking something non-obvious).

**Comment by traversaro** [comment]
> I think it might be reasonable here to just patch the generation of the CMake config on OSX, ideally coupled with an upstream issue discussing the situation (perhaps I'm overlooking something non-obvious).

Thanks. I reported the issue upstream in https://github.com/libsdl-org/SDL_ttf/issues/347, I can look into the patch even if at the moment I do not have easy access (or way to virtualize) to a macOS machine.
